# version: "3"

services:
  rocky_one:
    image: rockylinux:9
    container_name: rk_uno
    restart: on-failure
    command: ["sleep", "infinity"]
    networks:
      - rockyNet

  rocky_two:
    image: rockylinux:9
    container_name: rk_dos
    restart: on-failure
    command: ["sleep", "infinity"]
    networks:
      - rockyNet

  rocky_three:
    image: rockylinux:9
    container_name: rk_tres
    restart: on-failure
    command: ["sleep", "infinity"]
    networks:
      - rockyNet

  httpd:
    image: httpd
    container_name: httpd
    restart: on-failure
    volumes:
      -  /root/httpd/:/usr/local/apache2/htdocs/
    ports:
      - "8081:80"

  nginx:
    image: nginx
    container_name: nginx
    restart: on-failure
    volumes:
      -  nginx_volume:/usr/share/nginx/html/
    ports:
      - "8082:80"

volumes:
  nginx_volume:
    external: true

networks:
  rockyNet:
    name: rockyNet
